name: CI pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn compile -Dmaven.test.skip=true

  test:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Test with maven
        run: mvn -Dtest=\!TestPerformance verify

  package:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: github
          setting-path: ${{ github.workspace }}
      - name: Package
        run: mvn -B package -Dmaven.test.skip=true --file pom.xml
      - name: Publish package
        run: mvn -B deploy -Dmaven.test.skip=true -s $GITHUB_WORSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}